### ISSUE TITLE
login ไม่ผ่าน

### ISSUE THREAD

**Issue by NiponJaiboon** [yogolas/c2m#1]
ผม confix localhost ใหม่ โดยใส่ port เข้าไปเพิ่มเช่น 8080  แล้วจะ login เข้า http://localhost:8080/c2m/admin/login ด้วย User : admin password : admin แต่ เจอ error 
------------------------
A PHP Error was encountered

Severity: Warning

Message: mysqli::real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES)

Filename: mysqli/mysqli_driver.php

Line Number: 201

Backtrace:

File: D:\Work\iDev\Web\xampp\htdocs\c2m\application\controllers\storemanager\Login_submit.php
Line: 7
Function: database

File: D:\Work\iDev\Web\xampp\htdocs\c2m\index.php
Line: 315
Function: require_once

A Database Error Occurred

Unable to connect to your database server using the provided settings.

Filename: D:/Work/iDev/Web/xampp/htdocs/c2m/system/database/DB_driver.php

Line Number: 436
------------------------

**Comment by yogolas** [comment]
ปัญหา คือ การตั้งค่าฐานข้อมูลไม่ถูกต้อง
การแก้ปัญหาคือ ตั้งค่ารหัสผ่านฐานข้อมูลให้ถูกต้อง เข้าไปที่โฟลเดอร์  c2m\application\config  เปิดไฟล์ database.php   ตรวจสอบรหัสผ่านฐานข้อมูล password  

หรือ

uninstall  ลบไฟล์ ออกให้หมด  แล้วทำการติดตั้งใหม่ตามขั้นตอนในไฟล์  วิธีการติดตั้ง  ตรวจสอบขั้นตอนใส่ รหัสผ่านฐานข้อมูลให้แนใจว่าเป็น  12345678

**Comment by joomlacorner** [comment]
สังเกตุเจอว่า url มันวิ่งกลับมาที่ localhost โดยไม่มี  port  ที่ตั้งไว้ครับ  เช่น localhost:8888/c2m  ปุ่ม link หรือเวลา login มันจะเหลือแค่ localhost/c2m เฉยๆ ครับ

**Comment by yogolas** [comment]
ตั้งค่า url ได้ที่ application/core ไฟล์ My_controller.php

**Comment by NiponJaiboon** [comment]
@yogolas  แก้ไขได้แล้ว โดยแก้ไขที่ c2m\application\config เปิดไฟล์ database.php แล้วเปลี่ยน password
